apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: prometheus-del
 labels:
  app: prometheus
spec:
 replicas: 1
 selector:
  matchLabels:
   app: prometheus
  matchExpressions:
   - {key: app,operator: In,values: [prometheus]}
 template:
  metadata:
   name: prometheus-del
   labels:
     app: prometheus
  spec:
    containers:
    - name: prometheus-pod
      image: docker.io/prom/prometheus
      resources:
        limits:
         cpu: 500m
         memory: 500Mi
        requests:
         cpu: 250m
         memory: 256Mi
      ports:
      - containerPort: 9090
      volumeMounts:
      - name: prometh-v
        mountPath: /prometheus
    volumes:
    - name: prometh-v
      emptyDir: {}
